#!/bin/bash

set -x

 . /usr/share/3pl-crons/db/db_config.sh

CURR_TIME=$(date +"%Y-%m-%d_%H-%M-%S")
DATE=`date +"%F" `

shipping_lite_1_ws_user=shipping_lite_1_ws_ro
shipping_lite_1_ws_pwd=nMiTqb175Q
shipping_lite_1_ws_host=10.24.32.22
shipping_lite_1_ws_db=shipping_lite_1
shipping_lite_1_ws_port=4000

shipping_lite_2_ws_user=shipping_lite_2_ws_ro
shipping_lite_2_ws_pwd=rsr4p0pQee
shipping_lite_2_ws_host=10.24.32.22
shipping_lite_2_ws_db=shipping_lite_2
shipping_lite_1_ws_port=4000

shipping_lite_3_ws_user=shipping_lite_3_ws_ro
shipping_lite_3_ws_pwd=hINYqZ9FtV
shipping_lite_3_ws_host=10.24.32.22
shipping_lite_3_ws_db=shipping_lite_3
shipping_lite_1_ws_port=4000

shipping_lite_4_ws_user=shipping_lite_4_ws_ro
shipping_lite_4_ws_pwd=VbOz5Ake2B
shipping_lite_4_ws_host=10.24.32.22
shipping_lite_4_ws_db=shipping_lite_4
shipping_lite_1_ws_port=4000

shipping_lite_5_ws_user=shipping_lite_5_ws_ro
shipping_lite_5_ws_pwd=ApE5hTRtce
shipping_lite_5_ws_host=10.24.32.22
shipping_lite_5_ws_db=shipping_lite_5
shipping_lite_1_ws_port=4000

shipping_lite_6_ws_user=shipping_lite_6_ws_ro
shipping_lite_6_ws_pwd=CXl4Fhs4b7
shipping_lite_6_ws_host=10.24.32.22
shipping_lite_6_ws_db=shipping_lite_6
shipping_lite_1_ws_port=4000

export MAILTO="jaya.meesal.vc@flipkart.com"
export SUBJECT="message_id"


CWD="/home/jaya.meesal.vc/message_id"
input_file_name=$CWD/s
comma_separated_file_input="commaseparated_data_$DATE"

awk -F "<>" '{print $1}' $input_file_name |awk '{printf("'"'"'%s'"'"',", $0)} END{print ""}' |sed -e 's/^/'\('/g' |sed -e 's/$/'\)'/g' |sed 's/\,)/\)/' > $comma_separated_file_input

echo "$comma_separated_file_input"

for shard in {1..6}; do
Query="SELECT s.vendorTrackingId, sh.status, CONCAT('shard${shard}_', sh.id, ',', sh.createdAt) AS concatenated_value
FROM Shipments s
JOIN ShipmentStatusHistories sh ON s.serviceRequestId = sh.parentSrId
WHERE s.vendorTrackingId IN $(cat $comma_separated_file_input) and sh.status in ('rvp_cancelled','RTO_Completed','rvp_handover_completed');"

echo "$Query" | mysql -N -u$decoded_shippinglite1_user -p$decoded_shipping_lite_1_pass -h$shippinglite1_ro_ip shipping_lite_${shard} >>$CWD/data${shard}.csv
echo "$Query" | mysql -N -u$decoded_shippinglite2_user -p$decoded_shipping_lite_2_pass -h$shippinglite2_ro_ip shipping_lite_${shard} >>$CWD/data${shard}.csv
echo "$Query" | mysql -N -u$decoded_shippinglite3_user -p$decoded_shipping_lite_3_pass -h$shippinglite3_ro_ip shipping_lite_${shard} >>$CWD/data${shard}.csv
echo "$Query" | mysql -N -u$decoded_shippinglite4_user -p$decoded_shipping_lite_4_pass -h$shippinglite4_ro_ip shipping_lite_${shard} >>$CWD/data${shard}.csv
echo "$Query" | mysql -N -u$decoded_shippinglite5_user -p$decoded_shipping_lite_5_pass -h$shippinglite5_ro_ip shipping_lite_${shard} >>$CWD/data${shard}.csv
echo "$Query" | mysql -N -u$decoded_shippinglite6_user -p$decoded_shipping_lite_6_pass -h$shippinglite6_ro_ip shipping_lite_${shard} >>$CWD/data${shard}.csv
done

echo "$Query" |mysql -N  -u$shipping_lite_1_ws_user -p$shipping_lite_1_ws_pwd -h$shipping_lite_1_ws_host $shipping_lite_1_ws_db --port=4000 >>$CWD/data7.csv
echo "$Query" |mysql -N  -u$shipping_lite_2_ws_user -p$shipping_lite_2_ws_pwd -h$shipping_lite_1_ws_host $shipping_lite_2_ws_db --port=4000 >>$CWD/data8.csv
echo "$Query" |mysql -N  -u$shipping_lite_3_ws_user -p$shipping_lite_3_ws_pwd -h$shipping_lite_1_ws_host $shipping_lite_3_ws_db --port=4000 >>$CWD/data9.csv
echo "$Query" |mysql -N  -u$shipping_lite_4_ws_user -p$shipping_lite_4_ws_pwd -h$shipping_lite_1_ws_host $shipping_lite_4_ws_db --port=4000 >>$CWD/data10.csv
echo "$Query" |mysql -N  -u$shipping_lite_5_ws_user -p$shipping_lite_5_ws_pwd -h$shipping_lite_1_ws_host $shipping_lite_5_ws_db --port=4000 >>$CWD/data11.csv
echo "$Query" |mysql -N  -u$shipping_lite_6_ws_user -p$shipping_lite_6_ws_pwd -h$shipping_lite_1_ws_host $shipping_lite_6_ws_db --port=4000 >>$CWD/data12.csv


cat $CWD/data*.csv > $CWD/lite_payload.csv
